version: "3"

services:
  #serivce: 
  ktn-game-api:
    image: ktn-dapp-api
    build: 
      context: .
      dockerfile: Dockerfile-server
    restart: always
    volumes:
      - ./:/webapps
    ports:
      - 6007:5005
    networks:
      - base-network
    command: gunicorn --bind 0.0.0.0:5005 --workers=1 main:app --log-level=debug -c conf/gunicorn.py --timeout 0
  
  
  # ktn-game-api-queue-worker:
  #   image: ktn-dapp-api
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile-server
  #   restart: always
  #   volumes:
  #     - ./:/webapps
  #   networks:
  #     - base-network
  #   command: celery --app worker worker -Q katana-dapp-dapp-api-queue -l INFO -c 4
networks:
  base-network:
    external: true

