version: "3"

services:
  #serivce: 
  ktn-game-api:
    image: [IMAGE_REPO]
#    build: 
#      context: .
#      dockerfile: Dockerfile-server
    restart: always
#    volumes:
#      - ./:/webapps

    ports:
      - 6001:5005
    networks:
      - base-network
    command: gunicorn --bind 0.0.0.0:5005 --workers=3 main:app --log-level=debug -c conf/gunicorn.py --timeout 0
  
  
  ktn-game-api-queue-worker:
    image: [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q katana-game-api-queue -l INFO -c 4
networks:
  base-network:
    external: true

